### PR TITLE
Update mods_to_dc.xsl to version 1.8

### PR DESCRIPTION
**Pull request by bondjimbond**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2148

# What does this Pull Request do?

Updates the included mods_to_dc.xsl to the latest version (from 1.4/1.6 depending on which changelog you look at, to 1.8).

The version currently bundled with this module is outdated, and contains numerous errors. Updating to the corrected version should alleviate some of the complaints we get about the default transforms.

# What's new?
Replaces the mods_to_dc.xsl file with the current version from Library of Congress.

Effects: newly-ingested MODS will generate better-quality DC.

Possible negative effects: newer records may not have the same errors as the older records. But we don't want to perpetuate errors, do we?

# How should this be tested?

- Ingest an object, filling out all MODS fields in any working form (especially the hierarchicalGeographic/province field and any other modified fields in the changelog)
- View the transformed DC
- Check out this branch
- Edit MODS
- View transformed DC, make sure it looks OK

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bondjimbond good call!!. Can you please add some output comparison? Does this XSLT assume we are using MODS 3.5 or 3.6? Having consistent DC is for sure some of our concerns here and I'm pretty sure people would like to make sure their DC looks (and indexes) the same way. Also, are you going for the one inside importer and batch also? I would suggest "yes" since those modules use their own and you want DC datastreams to look uniform all over Islandora. Thanks for doing this!

**Comment by bondjimbond** [comment]
@DiegoPino The new transform isn't perfect either, but is better. Ran it through my custom MODS form for artwork objects. 

In this case, the primary differences are the elimination of a bunch of empty `<dc:subject></dc:subject>` elements, and the addition of the province (Ontario) to the dc:coverage element. (In the original, province is missing because of the aforementioned typo.)

It would be difficult to get a comprehensive document to show all the changes, but this hopefully should suffice to show that there is a difference, and that the newer one is better.

Original:
```
<dc:subject>Culturalcontext</dc:subject>
  <dc:subject>Style/period</dc:subject>
  <dc:subject>Topic2</dc:subject>
  <dc:subject>Topic1</dc:subject>
  <dc:subject></dc:subject>
  <dc:subject></dc:subject>
  <dc:subject></dc:subject>
  <dc:subject></dc:subject>
  <dc:subject></dc:subject>
  <dc:subject>Lastname, Firstname</dc:subject>
  <dc:subject>Lastname, Firstname</dc:subject>

...
     <dc:coverage>Geographictopic 2</dc:coverage>
  <dc:coverage>Geographictopic 1</dc:coverage>
  <dc:coverage>Temporaltopic2</dc:coverage>
  <dc:coverage>Temporaltopic</dc:coverage>
<dc:coverage>
North America--Canada--York Region--GTA--Toronto
</dc:coverage>
 <dc:coverage>49.2763943,-123.1246651</dc:coverage>
```

New transform:
```
  <dc:subject>Culturalcontext</dc:subject>
  <dc:subject>Style/period</dc:subject>
  <dc:subject>Topic2</dc:subject>
  <dc:subject>Topic1</dc:subject>
  <dc:subject>Lastname, Firstname</dc:subject>
  <dc:subject>Lastname, Firstname</dc:subject>
... 
     <dc:coverage>Geographictopic 2</dc:coverage> 
<dc:coverage>Geographictopic 1</dc:coverage>
<dc:coverage>Temporaltopic</dc:coverage>
<dc:coverage>Temporaltopic2</dc:coverage>
<dc:coverage>
North America--Canada--Ontario--York Region--GTA--Toronto
</dc:coverage>
 <dc:coverage>49.2763943,-123.1246651</dc:coverage>
```

**Comment by bondjimbond** [comment]
@DiegoPino 

> Does this XSLT assume we are using MODS 3.5 or 3.6? 

3.5 -- [LOC's list of xsl files](https://www.loc.gov/standards/mods/mods-conversions.html) only include 3.2, 3.4, and 3.5.

> Having consistent DC is for sure some of our concerns here and I'm pretty sure people would like to make sure their DC looks (and indexes) the same way. 

Agreed. I think for sure we want to update to the better (correct) version for HEAD and the next release, it's just a matter of making sure upgrading sites are aware of the change.

> Also, are you going for the one inside importer and batch also? I would suggest "yes" since those modules use their own and you want DC datastreams to look uniform all over Islandora. 

I could -- if this one gets approval to merge, I'll open a PR for the other two.

BUT on that topic - perhaps this would be an opportunity to instead point all of the modules that include a mods_to_dc.xsl file to one single shared file?

**Comment by DiegoPino** [comment]
@bondjimbond ```<dc:coverage>49.2763943,-123.1246651</dc:coverage>``` missing? i need to  make a diff to see what changed, sadly today is not a good day. 

I agree with you on all the other matters 👍  the question is where we put that XSLT so its common to all other ones? I would say as low in the food chain as possible, so I would (almost) go for Islandora core... but other @Islandora/7-x-1-x-committers can have different ways on this. I think I remember @patdunlavey had a solution to allow simply management of that XSLT.. ☎️ ping ping!

**Comment by mjordan** [comment]
+1 to centralizing this stylesheet. It can always be overridden by XML Forms if necessary, correct?

**Comment by bondjimbond** [comment]
@DiegoPino 

> <dc:coverage>49.2763943,-123.1246651</dc:coverage> missing? i

Sorry, not missing, just missing from my paste.

My copies of the files generated are identical except that the new transform eliminates the empty subject sets and includes the missing province.

**Comment by bondjimbond** [comment]
@mjordan 
> +1 to centralizing this stylesheet. It can always be overridden by XML Forms if necessary, correct?

Correct! Although the way that works is complex and very poorly documented, so some work needs to be done on that too.

@DiegoPino 

> the question is where we put that XSLT so its common to all other ones? I would say as low in the food chain as possible, so I would (almost) go for Islandora core...

Core seems like the right place to me. After all, transforming to DC is kind of a core function, isn't it?

**Comment by bondjimbond** [comment]
@DiegoPino @mjordan Possible avenue for sites to resolve to the problem of consistent DC: https://github.com/qadan/islandora_batch_derivative_trigger

Sites would only have an inconsistent DC problem if they were using just the default XSLT -- if using a custom one, then updating to v1.8 would not affect them regardless. So, pointing upgrading sites to Islandora Batch Derivative Trigger would help reassure anyone concerned about consistency.

**Comment by bondjimbond** [comment]
@DiegoPino No issues raised at the committers' call yesterday... Would we be ready to merge this? Or should I be adding Importer and Batch replacements to this as well?

Centralizing them would be a separate and more complex PR, I think; I'd see this one as a first step.

**Comment by DiegoPino** [comment]
@bondjimbond if you go for this without centralizing you need to update all the others. We can't allow different DC's depending on how you ingest, at least if you are using vanilla. let me know when you have all PR and i will review then and merge them at once. thanks!

**Comment by bondjimbond** [comment]
@DiegoPino PRs added for Batch and Importer. After this is merged, we can discuss the centralization issue in Jira.

**Review by DiegoPino — APPROVED** [review]
Based on latest 1.8 version from http://www.loc.gov/standards/mods/v3/MODS3-5_DC_XSLT1-0.xsl.
Looks good.

**Pull request merged**
