### PR TITLE
add trim to path and value

### PR DESCRIPTION
**Pull request by nhart**
when there's a leading space in the value (in create control) the ingest occasionally fails 

Error 324 (net::ERR_EMPTY_RESPONSE): The server closed the connection without sending any data.

https://jira.duraspace.org/browse/ISLANDORA-711

### CODE REVIEW

**Comment by jonathangreen** [comment]
Change looks good. I wonder if this is a problem in D7 as well?

**Comment by jonathangreen** [comment]
I'm fairly sure the line where we added the trim exists in both 6 and 7

**Comment by nhart** [comment]
Ok. I will have a look.

**Comment by nhart** [comment]
Yes, 7.x is also broken. when there's a leading space in the value you can't ingest. sending pull request shortly.

**Pull request merged**
