### PR TITLE
Enable pretty formatting

### PR DESCRIPTION
**Pull request by PaulVanSchayck**
**JIRA Ticket**: ISLANDORA-1700
# What does this Pull Request do?

This enables pretty formatting for the output of XML-forms.
# What's new?

A new function that creates the `DOMDocument` 
# How should this be tested?

I'm testing outside of the context of Islandora. I'm using XML-forms separate. So I do not have a procedure to test within Islandora. 

Outside of Islandora you can see the output of saveXML()

```
$xml_form = new XMLForm($form_state);
$document = $xml_form->submit($form, $form_state);
$document->saveXML()
```
# Interested parties

@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by manez** [comment]
Hi @PaulVanSchayck ! Thank for this contribution. In order to have it merged into Islandora, we'll need to have a [Contributor License Agreement](http://islandora.ca/sites/default/files/islandora_cla.pdf) from you. Or, if this was done on behalf of your employer, a [Corporate Contributor License Agreement](http://islandora.ca/sites/default/files/islandora_ccla.pdf). You can send that along to me at manez@islandora.ca and I'd be happy to get it squared away or answer any questions.

Thanks!

**Comment by PaulVanSchayck** [comment]
Dear @ruebot and @manez,

I'm going to the process of having this contributor license approved. This may take a while.

Meanwhile, I tried to signup for JIRA, but got this message "This installation of Confluence is not set up to permit public signup. Please contact the site administrators for more information.". I've used this page:
https://wiki.duraspace.org/signup.action

Are there any comments remaining regarding the code or style?

**Comment by manez** [comment]
@PaulVanSchayck , fire me an email at manez@islandora.ca and I'll set you up with a registration token 😄

**Comment by DiegoPino** [comment]
@PaulVanSchayck hi!. @ruebot added you to JIRA, so you can update the status at https://jira.duraspace.org/browse/ISLANDORA-1700 (push the start working button and then the ready for review). I will review this (it's fine code by the way, just needed formality). Thanks!

**Comment by PaulVanSchayck** [comment]
Hi @DiegoPino 

I've pressed the Start Work button. There is no Ready for Review button, only a Start Review button which asks me for a Resolution.

**Comment by DiegoPino** [comment]
@PaulVanSchayck JIRA is sometimes sentimental. I'm fine with this pull. Will merge since it does not break nor alter anything strange and it's also very helpful and also had enough time for others to review.

**Comment by DiegoPino** [comment]
@PaulVanSchayck congrats on your first merged pull. 🎆  I hope to see a lot more going that route 👍

**Pull request merged**
