### PR TITLE
re-adding drag and drop fields

### PR DESCRIPTION
**Pull request by qadan**
got a bit broke in https://jira.duraspace.org/browse/ISLANDORA-1380

### CODE REVIEW

**Comment by qadan** [comment]
The invocation of the drag and drop plugin gets overwritten by the fix to the thingy, so drag-and-drop of form elements stopped working

**Comment by willtp87** [comment]
https://jira.duraspace.org/browse/ISLANDORA-1449

**Comment by DiegoPino** [comment]
Looks fine, will re-test just to be sure.

**Comment by willtp87** [comment]
I've tested this and it looks good to me.

**Pull request merged**
